#!name=Enhancement
#!desc=Route special services to available country.

[Rule]
# APNs
DOMAIN-SUFFIX,push.apple.com,PROXY
DOMAIN-SUFFIX,akadns.net,PROXY
DOMAIN-KEYWORD,apple.com.edgekey.net,PROXY

IP-CIDR,17.249.0.0/16,PROXY,no-resolve
IP-CIDR,17.252.0.0/16,PROXY,no-resolve
IP-CIDR,17.57.144.0/22,PROXY,no-resolve
IP-CIDR,17.188.128.0/18,PROXY,no-resolve
IP-CIDR,17.188.20.0/23,PROXY,no-resolve

IP-CIDR6,2620:149:a44::/48,PROXY,no-resolve
IP-CIDR6,2403:300:a42::/48,PROXY,no-resolve
IP-CIDR6,2403:300:a51::/48,PROXY,no-resolve
IP-CIDR6,2a01:b740:a42::/48,PROXY,no-resolve

# Google
# RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Google/Google.list,US

# AI
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/OpenAI/OpenAI.list,US
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Claude/Claude.list,US
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Anthropic/Anthropic.list,US

#TikTok
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/TikTok/TikTok.list,US

# PayPal
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/PayPal/PayPal.list,US

# SpaceX & Starlink
DOMAIN-SUFFIX,spacex.com,US
DOMAIN-SUFFIX,starlink.com,US
DOMAIN-SUFFIX,starlinkisp.net,US
DOMAIN-SUFFIX,starlinkspace.com,US
DOMAIN-SUFFIX,sxndata.com,US
DOMAIN-SUFFIX,sxn.io,US
DOMAIN-KEYWORD,spacex,US
DOMAIN-KEYWORD,starlink,US
