#!name=HK-Compensation
#!desc=Route special services to available country.

[Rule]

# AI
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/OpenAI/OpenAI.list,US
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Claude/Claude.list,US
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Anthropic/Anthropic.list,US
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Gemini/Gemini.list,US

#TikTok
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/TikTok/TikTok.list,US

# PayPal
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/PayPal/PayPal.list,US

# SpaceX & Starlink
DOMAIN-SUFFIX,spacex.com,US
DOMAIN-SUFFIX,starlink.com,US
DOMAIN-SUFFIX,starlinkisp.net,US
DOMAIN-SUFFIX,starlinkspace.com,US
DOMAIN-SUFFIX,sxndata.com,US
DOMAIN-SUFFIX,sxn.io,US
DOMAIN-KEYWORD,spacex,US
DOMAIN-KEYWORD,starlink,US

